AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String
  ACMCertificateArn:
    Type: String

Resources:
  RecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expires
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: created
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: created
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      CodeUri: .
      Handler: main
      Runtime: provided.al2
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref RecordsTable
        - S3CrudPolicy:
            BucketName: !Ref RootBucket
      Environment:
        Variables:
          TABLE_NAME: !Ref RecordsTable
          BUCKET_NAME: !Ref RootBucket
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref Gateway
            Path: /{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: makefile

  Gateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref ACMCertificateArn

Outputs:
  GatewayEndPoint:
    Value: !Sub "https://${Gateway}.execute-api.${AWS::Region}.amazonaws.com/"
  
